
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 172.16.0.0/12

lovelace:
  mode: yaml
  dashboards:
    lovelace-default:
      mode: yaml
      filename: ui-lovelace.yaml
      title: Dashboard
      show_in_sidebar: true
  resources:
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/lovelace-mushroom/mushroom.js
      type: module
    - url: /hacsfiles/mini-graph-card/mini-graph-card-bundle.js
      type: module
    - url: /hacsfiles/scheduler-card/scheduler-card.js
      type: module
    - url: /hacsfiles/swipe-card/swipe-card.js
      type: module
    - url: /webrtc/webrtc-camera.js
      type: module
    - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
      type: module

lovelace_gen: !include dashboard/auto-config.yaml

notify:
  - name: all_phones
    platform: group
    services:
      - service: mobile_app_chris
      - service: mobile_app_bex
